### ISSUE TITLE
Can it work?

### ISSUE THREAD

**Issue by chiro2001** [fakeboboliu/wenku8epub#1]
环境：Win10 64bit 4Gb Ram
命令：wenku8.exe -u https://www.wenku8.net/book/1359.htm -o o.epub
输出：

> D:\Downloads_win10>wenku8.exe -u https://www.wenku8.net/book/1359.htm -o o.epub
> time="2019-04-05T04:45:50+08:00" level=info msg="Loaded template." name=chapter.html
> time="2019-04-05T04:45:50+08:00" level=info msg="Loaded template." name=container.xml
> time="2019-04-05T04:45:50+08:00" level=info msg="Loaded template." name=fb.opf
> time="2019-04-05T04:45:50+08:00" level=info msg="Loaded template." name=main.css
> time="2019-04-05T04:45:50+08:00" level=info msg="Loaded template." name=mimetype
> time="2019-04-05T04:45:50+08:00" level=info msg="Loaded template." name=nav.html
> time="2019-04-05T04:45:50+08:00" level=info msg="Loaded selectors." count=6
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> main.getWenku8(0xc00001c300, 0x24, 0xc000202400)
>         C:/Users/boboliu/go/src/github.com/popu125/wenku8epub/wenku8.go:32 +0x7ea
> main.main.func1(0xc000216210, 0x0, 0x0)
>         C:/Users/boboliu/go/src/github.com/popu125/wenku8epub/main.go:27 +0x1f6
> github.com/mkideal/cli.(*Command).RunWith(0xc0003c7d40, 0xc00007e010, 0x4, 0x7, 0xa8ff60, 0xc0001e2410, 0x0, 0x0, 0x0, 0x0, ...)
>         C:/Users/boboliu/go/src/github.com/mkideal/cli/command.go:220 +0x269
> github.com/mkideal/cli.(*Command).Run(...)
>         C:/Users/boboliu/go/src/github.com/mkideal/cli/command.go:177
> github.com/mkideal/cli.RunWithArgs(0x91cba0, 0xc0002a68c0, 0xc00007e000, 0x5, 0x8, 0xa00d50, 0x0, 0x0, 0x0, 0xc00004c058)
>         C:/Users/boboliu/go/src/github.com/mkideal/cli/cli.go:30 +0x1a7
> github.com/mkideal/cli.Run(...)
>         C:/Users/boboliu/go/src/github.com/mkideal/cli/cli.go:15
> main.main()
>         C:/Users/boboliu/go/src/github.com/popu125/wenku8epub/main.go:18 +0x86

是不是我调用错了？为什么会数组越界啊...
建议吧用法举个栗子放在-h里面。

**Comment by fakeboboliu** [comment]
已经更新了readme，抱歉没说清楚（以为没人会用的辣鸡作者）
